### ISSUE TITLE
Error collect2.exe during compilation

### ISSUE THREAD

**Issue by fxkdev** [GENIVI/dlt-viewer#100]
Hi,

I tried to build dlt-viewer 2.19.0 with Qt Creator (Qt5.12.4) and got the following error (that did not happen with dlt-viewer 2.18.0 and the same project-configuration).

![image](https://user-images.githubusercontent.com/49194924/78768458-3df3ed80-798c-11ea-8503-10438ce1ea7e.png)

Do you have any idea what it is related to? Is my project bad configured or can it be linked to a missing library?

Thank you for your support

**Comment by alexmucde** [comment]
Hi @fxkdev. We currently do not support MinGW builds. Please switch to MSVC build on Windows platform.

**Comment by alexmucde** [comment]
No official support for MinGW. please provide pull request if still needed.
