### ISSUE TITLE
sorting by time changes marked files

### ISSUE THREAD

**Issue by SimonPreisinger** [GENIVI/dlt-viewer#103]
Select a index id: CTRL+G => 271384
Mark the index: RIGHT MOUSE BUTTON => mark
Goto Filter => sort by time

Issue
another index id is marked
Expected:
line with index id 271384 should be marked.

**Comment by alexmucde** [comment]
The current behaviour is that the number of the message in the Tableview is stored. If the sorting is changed, another message will be marked. See also doumentation 2.3.3 Project Other Settings 12.

To solve this issue implementation must be changed to store message index.

Please provide a pull request to improve this issue.

**Comment by alexmucde** [comment]
No progress on this issue. Please reopen if a solution will be available.
