### ISSUE TITLE
File transfer plugin does not show received files

### ISSUE THREAD

**Issue by karthikshanmugam** [GENIVI/dlt-viewer#108]
DLT Viewer: 2.20.0
DLT Daemon: 2.18.5

I can see the logs in the viewer window, but the plugin does not recogonize the file 

![image](https://user-images.githubusercontent.com/104696/87239360-e4d4a380-c42b-11ea-8e46-890c74c96bc2.png)

Best regards,
Karthik

**Comment by alexmucde** [comment]
Need more information (e.g. DLT test file) to check this issue.

**Comment by alexmucde** [comment]
Not enough information to anaylse issue.
