### ISSUE TITLE
View doesn't follow current cursor position.

### ISSUE THREAD

**Issue by hkjin81** [GENIVI/dlt-viewer#118]
Precondition:
Version 2.18, 2.19, 2.20, 2.20.1
Qt 5.15
Windows 10

Steps:
1. Open a dlt log file.
2. Select one line by mouse.
3. Press down arrow key by keyboard until view scroll happen.

Expected result:
View scrolled automatically to keep current line cursor visible.

Actual result:
View doesn't follow the cursor and the cursor disappeared from current view.

Etc:
This problem make me to lose current scroll position after "Apply Configuration" clicked.
It goes to the top so I have to remember the line before "Apply Configuration" and scroll to the line by myself.
It's very annoying.

Please feel free to ask me further information.

ADD:
It's doesn't work well on linux platform either. Something was different when I tested on linux before.(I've deleted comment about linux platform)
I couldn't figure out what was the factor.
Currently, the problem happens on both platform.

**Comment by alexmucde** [comment]
Will this issue be fixed with #120

**Comment by alexmucde** [comment]
This issue only happens, when column "index" is disabled.
