### ISSUE TITLE
[Bug] DLT Viewer crashes if filter is changed while index is created

### ISSUE THREAD

**Issue by phl256** [GENIVI/dlt-viewer#122]
DLT Viewer Version : 2.20.2

- Load a large DLT file
-> Index is created (status bar shows CI with percent)
- Change the current filter while CI is still shown
-> DLT Viewer crashes

This is reproducible on Windows.

**Comment by alexmucde** [comment]
I was not able to reproduce the issue in Windows. I loaded a very huge (1gb) DLT File. During indexing i changed the filter, added new filters and removed existing filters, but no crash happened. I checked the source code and the filters are copied during the beginning of the indexing. Perhaps there is another side effect of another action.

**Comment by alexmucde** [comment]
Not reproducible.
