### ISSUE TITLE
Search results table shows white text on white background when Auto mark is enabled

### ISSUE THREAD

**Issue by 4og** [GENIVI/dlt-viewer#138]
When the "Auto mark fatal/error messages" option is enabled in the settings, the Search Results table shows found error messages as white text on white background. This makes them unreadable.

**Expected:**
The background color of Auto-marked messages is preserved in the Search Results table.

Tested version: a0be13f30a243a1fcc926a92ebccb155c529edd9
Ubuntu 20.04, Qt 5.12.8, GCC 9.3.0

**Comment by alexmucde** [comment]
Reproduced this issue also in Windows. A pull request with a bug fix would be great.
