### ISSUE TITLE
macOS icon missing

### ISSUE THREAD

**Issue by hannesa2** [GENIVI/dlt-viewer#141]
Hi, first of all: Thank you to make it public !

I build it with macOS and it builds and runs, but the icon is not available

<img width="294" alt="image" src="https://user-images.githubusercontent.com/3314607/99932319-ef973180-2d57-11eb-8891-8b15598188f6.png">

Sorry, I've too less knowledge with `qt` to fix it

**Comment by alexmucde** [comment]
Hi, i am not familiar with macOS. I have found the following instruction:

https://doc.qt.io/archives/qt-5.11/appicon.html

If you use qmake you need to do the following:

At first you need an icns file, which should be already in \src\icon .
Then you have to add to the src/src.pro file.
ICON = icon/icon.icns

If you are using cmake it will be more complicate, please see the instructions.

Please try this if it works you or me can create a pull request.

**Comment by hannesa2** [comment]
To give anyone the chance to follow, I made a non-working pull request https://github.com/GENIVI/dlt-viewer/pull/149

**Comment by alexmucde** [comment]
@hannesa2 so this is not fixed yet?
