### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jjardon** [GENIVI/dlt-viewer#16]
There has been a lot of improvements in the last 2 years since v2.18; is there any plans to a new release?

Some people is asking for an update in the Arch package :) : https://aur.archlinux.org/packages/dlt-viewer/

**Comment by jeremiah** [comment]
From my understanding, there is no planned new release in the pipeline. But that doesn't mean that one can be done, I'll ask the maintainers to review your request.

**Comment by jjardon** [comment]
Hey @jeremiah !

Not expectations really, but I'd like to use a tag instead a random commit to update the Arch package linked above

**Comment by AWWenzel** [comment]
Hi @jjardon, @jeremiah ,

i will talk to Gernot, who is doing the maintenance.
He already planned to create a 2.19.0 version.

    Alex

**Comment by shadamik** [comment]
What about a deb package? Are there any recipes available?

**Comment by jeremiah** [comment]
There are deb packages floating around. Because GENIVI builds its demonstrators from a source code build too we don't officially maintain deb packages but there are some built and we can provide some packaging artifacts. I'll try and gather that material.

**Comment by jeremiah** [comment]
Here is the Ubuntu PPA: https://launchpad.net/~genivi-ubuntu/+archive/ubuntu/utopic.ppa 
Unfortunately that only holds dlt-daemon and I think most folks want a package of dlt-viewer. I don't think that should be that hard to create, I'll look into it.

**Comment by aigarius** [comment]
I am planning on getting this in Debian as well. Not sure how hard the specifics of dlt-viewer and Qt will be, but help is for sure welcome.

**Comment by jeremiah** [comment]
I'm traveling at the moment, but when I'm back I plan to help as much as possible with testing (Arch packages, Debian packages, building from source) and will try and be a bridge between upstream and the distros. Fortunately we have a DLT maintainer in this thread so I'm hopeful that we can get some good, working packages out of this. :-)

**Comment by jjardon** [comment]
Thanks @jeremiah , a new tag would be enough in my case (Arch) :)

**Comment by GeniviDLTmaintainer** [comment]
The current plan is to prepare a new official release 2.19.0 until end of july 2019.

**Comment by alexmucde** [comment]
Released v2.19.0 now
