### ISSUE TITLE
Need some help to wetup Github Actions for CI builds

### ISSUE THREAD

**Issue by alexmucde** [GENIVI/dlt-viewer#164]
I need some help to create Github Actions for automatic builds as we do already with Appveyor and Travis. Hopefully Github Actions work smoother that the other ones. Three actions needed for:

- Ubuntu 20.04 LTS
- Windows MSVC 2015 or 2017
- MacOS

Please provide a pull request if possible.

**Comment by svlad-90** [comment]
Hi @alexmucde, unfortunately, currently I do not have the capacity to overtake this task, but I think I have an important input, which might make its implementation much easier.

My plugin already has CI builds, which are based on Github Actions:
https://github.com/svlad-90/DLT-Message-Analyzer/tree/master/.github/workflows

And the idea of my CI build is to fetch dlt-viewer, inject the plugin's repository into the "plugins" folder of the dlt-viewer, and build the dlt-viewer. Thus, actually, you can copy-paste my workflows, remove the steps related to injection of the dlt-message-analyzer - and you are done. Profit.

I'm supporting Linux & Windows builds. Currently no Mac. But you can have at least 2 builds out of 3 in ~1 hour of work. Also, be aware that I'm building dlt-viewer with Qt 5.15 & msvc 2019. But that is easily adjustable in the YAML files.

Hopefully, this input will help you to get things done with fewer efforts ☺
