### ISSUE TITLE
Download-able artifacts in Release

### ISSUE THREAD

**Issue by hannesa2** [GENIVI/dlt-viewer#172]
When you tell me what the artifacts for each/some platform/s I can make you an action on Github which provides it here https://github.com/GENIVI/dlt-viewer/releases

At least for macOS it's not a single file (and signing is an issue)

Here is an example https://github.com/ytai/ioio/releases/tag/6.1.0

**Comment by lukx** [comment]
I don't know whether this answers (part of) your question but:
"DLT SDK" is the dlt-viewer binary package for windows, 64 bit
"DLT Parser" is the dlt-parser binary package for windows, 64 bit

**Comment by hannesa2** [comment]
When  you go to pull request job detail (not release) eg https://github.com/GENIVI/dlt-viewer/runs/1747384132
you have the snapshots already there 

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/3314607/105473270-36909d00-5c9d-11eb-8423-576e2d274d37.png">

I can only test macOS, and there I've problems 
<img width="585" alt="image" src="https://user-images.githubusercontent.com/3314607/105473497-7a83a200-5c9d-11eb-8c97-1fac1341b1f7.png">

I can only confirm for macOS it's not working now 👎 

@lukx 
Please can you test on Windows the artifacts ?

Who can do this for Linux ?

**Comment by alexmucde** [comment]
Can we also use Github Actions to build on master the latest commit, as Appveyor and Travis did? I am currently downloading the Artifact, download is quiet slow.

**Comment by lukx** [comment]
@hannesa2 downloaded dlt-sdk from the run you linked, it starts normally (but I have no log available to actually test the programm)

**Comment by alexmucde** [comment]
Yes it works, also with log file.

![image](https://user-images.githubusercontent.com/22935478/105475151-5b860f80-5c9f-11eb-8002-de45b0a38145.png)

**Comment by hannesa2** [comment]
> Can we also use Github Actions to build on master the latest commit, as Appveyor and Travis did?

Here you go #176

**Comment by alexmucde** [comment]
Appveyor still builds, perhaps i have to delete the two remaining Webhooks in the project settings?

![image](https://user-images.githubusercontent.com/22935478/105486341-9cd1eb80-5cae-11eb-8c5f-eec61c215729.png)

**Comment by alexmucde** [comment]
Deleted some old Appveyor jobs in my Appveyor account, should not build anymore.

**Comment by alexmucde** [comment]
Are we finished with this issue?

**Comment by hannesa2** [comment]
You mean the "Download-able artifacts in Release" ?
No, I've no feedback from Linux and macOS doesn't work

But I could do it in the meantime for Windows only

**Comment by hannesa2** [comment]
### Linux
I checked on a Linux machine and generated Linux artifact starts. But you have to gave it `+x` permission in advance.
Maybe I will make a pull request with this last step.

### Release with artifacts

As long as we build release at least on 3 different os, I run into the issue that I've to collect from 3 machine the artifacts, but currently I don't now how to do that.
Collection in a pull request job is quite easy and already implemented.

**Comment by hannesa2** [comment]
I close this, because there is a pull request #184
