### ISSUE TITLE
Remove appveyor 

### ISSUE THREAD

**Issue by hannesa2** [GENIVI/dlt-viewer#185]
It's only annoying

<img width="450" alt="image" src="https://user-images.githubusercontent.com/3314607/109814884-4e115d00-7c2f-11eb-86e6-308f9902b2da.png">

**Comment by alexmucde** [comment]
@gunnarx Can you remove the AppVeyor build for DLT Viewer? We are using now Actions.

**Comment by alexmucde** [comment]
This was fixed by Gunnar.
