### ISSUE TITLE
Injection messages are one character longer than with dlt-control

### ISSUE THREAD

**Issue by jardous** [GENIVI/dlt-viewer#19]
Injection sent from DltViewer are one character longer than the same injection sent by dlt-control.

It looks like DltViewer adds "\0" and those messages have to be handled differently in a client app.

**Comment by GeniviDLTmaintainer** [comment]
@jardous Yes you are right. The null termination of the string is also send, This is unnecessary, because the control message ends after the string.
To keep it consistent with dlt-control i will remove it from DLT Viewer.

**Comment by AWWenzel** [comment]
I will improve this.

**Comment by GeniviDLTmaintainer** [comment]
Imrpoved, please check lattest version.

**Comment by GeniviDLTmaintainer** [comment]
Reopen if not working
