### ISSUE TITLE
Missing release 2.21.2

### ISSUE THREAD

**Issue by AlessandroBono** [GENIVI/dlt-viewer#191]
Yesterday I saw version 2.21.2 released and [I promptly made a Flathub release](https://github.com/flathub/org.genivi.DLTViewer/commit/0a8d55d4e8a650a2a65f7c4cc045453bb62fc8dc). Now I see that the release is no more present and the URL gives error 404. What happened?

**Comment by alexmucde** [comment]
Sorry for the confusion. The Release Tag is back. I wanted to try something with the CI build system, but it was not working.

**Comment by AlessandroBono** [comment]
Ok, thank you!
