### ISSUE TITLE
DLT-Viewer: How to apply parser to decode messages (Non Verbose Mode Plugin)

### ISSUE THREAD

**Issue by GirijaG** [GENIVI/dlt-viewer#197]
@Alexander Wenzel @philrob17  @jeremiah @jeremiah @tobsan @jjardon @jdehaan @neverpanic 
Team,

I need to do below actions in command line
<img width="960" alt="convert_DLT_CSVorTXT_Apply_parser" src="https://user-images.githubusercontent.com/6948213/113871406-7fea8600-97d0-11eb-8684-af2033bd2bf6.png">

To do so, I used below command at command prompt (Windows 10).
dlt_viewer.exe DLT_18_2_20.dlt -e "Non Verbose Mode Plugin|D:/DltViewer/DLT_PARSER_OUTPUT.xml|Apply Configuration"

But getting below error: 
<img width="249" alt="dlt_issue" src="https://user-images.githubusercontent.com/6948213/113871420-837e0d00-97d0-11eb-8ea3-899b2f9d539f.png">

Please help me out which command to use, to convert .dlt files to .csv/.txt files by applying the parser.

Without applying parser, below commands works:

1. dlt_viewer.exe -csv -c DLT_0_19_72_2.dlt dlt_csv.csv
2. dlt_viewer.exe -u -c DLT_0_19_72_2.dlt dlt_text.txt

Thanks and Regards
Girija

**Comment by alexmucde** [comment]
@GirijaG You cannot use the -e option to provide configuration files to plugins.
You have to load and activate a plugin in the DLT Viewer and store the configuration into a project file.
Then you can load the project by command line with the -p option.

Does this solve the issue?

**Comment by GirijaG** [comment]
> @GirijaG You cannot use the -e option to provide configuration files to plugins.
> You have to load and activate a plugin in the DLT Viewer and store the configuration into a project file.
> Then you can load the project by command line with the -p option.
> 
> Does this solve the issue?

Yes, thank you, 

dlt-viewer.exe -p dlt-parser.dlp -s -u -c DLT_0_19_73_3.dlt dlt.txt

the above command i m using to convert and it is working.

**Comment by Znzero** [comment]
> 

how to  load and activate a plugin in the DLT Viewer and store the configuration into a project file?
