### ISSUE TITLE
Is there any plan to build an android edition?

### ISSUE THREAD

**Issue by zeerd** [GENIVI/dlt-viewer#20]
So that we could do some debug over wifi with a cellphone or pad.

**Comment by zeerd** [comment]
Seems you have no plan, so I will see if I could do something.

**Comment by GeniviDLTmaintainer** [comment]
No plan up to now ...

**Comment by zeerd** [comment]
Ok, got it.

Er.. by the way, it is not an ad, but I made my own one last weeks.
https://github.com/zeerd/dlt-viewer-android

**Comment by GeniviDLTmaintainer** [comment]
Great !!!!
