### ISSUE TITLE
[Serial console] support baud rate 460800

### ISSUE THREAD

**Issue by windshining** [GENIVI/dlt-viewer#212]
there is a use case that our serial console is with baud rate 460800, which is currently not supported by DLT-viewer.

**Comment by alexmucde** [comment]
I have created a pull request. Please try it out if it works, when the build of the PR is inished. 

https://github.com/GENIVI/dlt-viewer/pull/213

**Comment by alexmucde** [comment]
@windshining Are you able to test it?
