### ISSUE TITLE
UDP reception breaks when filter set is changed

### ISSUE THREAD

**Issue by vrupanov** [GENIVI/dlt-viewer#28]
If messages are received via UDP multicast, and log is >400K, changing filter set and applying leads to loss of UDP connection.

**Comment by GeniviDLTmaintainer** [comment]
This looks like a performance issue, which requires a seperate thread for the reception of DLT messages. Currently all message reception is performed in the main thread. A bigger rework is needed.

**Comment by AWWenzel** [comment]
I will fix this.

**Comment by GeniviDLTmaintainer** [comment]
Does the Pull request "Fix the manual trigger to re-read data after reapplying filters #29" solve this issue?

**Comment by alexmucde** [comment]
Verfified on our CI and pushed to master.
For future improvement reception of messages must be handled in a separated thread.
