### ISSUE TITLE
Control response messages reporting errors are considered OK

### ISSUE THREAD

**Issue by YPRenault** [GENIVI/dlt-viewer#30]
The DLT daemon reports status in a control response message that is normally formed of 5 bytes: Service ID (4B) followed by the error status (1B).
The module qdltmsg extracts the information from the message, but this guy considers that the payload must be at least 6 bytes to grab the status at the 5th position, so the status is never read and reported by default as OK while it might not be.
Checkout: https://github.com/GENIVI/dlt-viewer/blob/master/qdlt/qdltmsg.cpp#L343

**Comment by AWWenzel** [comment]
@YPRenault You are right looks like an erro, i will fix this.

**Comment by GeniviDLTmaintainer** [comment]
Fixed, please check lattest version.

**Comment by GeniviDLTmaintainer** [comment]
Reopen if not working
