### ISSUE TITLE
GetLogInfo payload content is missing the last byte

### ISSUE THREAD

**Issue by vadrianc** [GENIVI/dlt-viewer#33]
Observed in DLT Viewer 2.18.0 STABLE

GetLogInfo (service ID 0x03) payload content is being displayed without the last byte from the payload:

![image](https://user-images.githubusercontent.com/13897757/59254177-614cef80-8c38-11e9-9e21-e2bd8d88fb71.png)

**Comment by AWWenzel** [comment]
@vadrianc I can repoduce the issue, i will fix it.

**Comment by GeniviDLTmaintainer** [comment]
Fixed, please check lattest version.

**Comment by GeniviDLTmaintainer** [comment]
Reopen if not working

**Comment by GeniviDLTmaintainer** [comment]
Reopen if not working
