### ISSUE TITLE
Unsigned integer not being decoded

### ISSUE THREAD

**Issue by vadrianc** [GENIVI/dlt-viewer#34]
Observed in DLT Viewer 2.18.0

I got a DLT file containing 4 DLT packets, each containing in the payload a single unsigned integer argument, 8-bit, 16-bit, 32-bit and 64-bit long. DLT Viewer decodes only the 8-bit long unsigned integer. If the packets are saved individually to a file, DLT Viewer displays each one, when opening the corresponding file. 

See [unsigned_int_arg.zip](https://github.com/GENIVI/dlt-viewer/files/3280888/unsigned_int_arg.zip)

**Comment by AWWenzel** [comment]
@vadrianc I tried your file with a Windows version of DLT Viewer 64 Bit. I can see all four lines. The first one has the value 18446744073709551615, the second 4294967295, the third 65535 and the last 255.
Perhaps you have some issues with the built in index cache. Please empty or disable the cache in the Settings.

**Comment by vadrianc** [comment]
@AWWenzel I tried to reproduce it again without clearing the cache as you suggest, but I was able to see all 4 DLT lines. Since I'm unable to reproduce it again, I believe the ticket can be closed.

**Comment by AWWenzel** [comment]
Cannot be reproduced.
