### ISSUE TITLE
 Unknown CMake command "QT5_WRAP_UI"

### ISSUE THREAD

**Issue by Mehmetcanss** [GENIVI/dlt-viewer#46]
I am not a cmake user, but I did the following in MacOs, which gave me the following error:

brew install qt
Qt5_DIR="/usr/local/opt/qt" cmake src/

Gives the following error:

CMake Error at CMakeLists.txt:22 (QT5_WRAP_UI):
  Unknown CMake command "QT5_WRAP_UI".

**Comment by syl22-00** [comment]
You are not pointing to the top level CMakeLists.txt file. you should point to the root folder of the source code, not the src/ folder.

**Comment by Mehmetcanss** [comment]
Thanks, it worked but only after I exported the QtDIR in my bash_profile

**Comment by sagaidakovskyi** [comment]
> You are not pointing to the top level CMakeLists.txt file. you should point to the root folder of the source code, not the src/ folder.

I have exported qt dir to bash profile:
export PATH="$PATH:/usr/local/opt/qt/bin"

However it is not clear what do you mean by "root folder of the source code". Is it directory above src/ ?

I am still getting Unknown CMake command "QT5_WRAP_UI"

**Comment by sagaidakovskyi** [comment]
It appeared that I had to unzip dlt-viewer from scratch, because cmake cache prevented from correct build of application on macOS

However here are my parameters from bash_profile in case anyone might require them:

export CMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.13.2/
export Qt5_DIR="/usr/local/Cellar/qt/5.13.2/"
export QtDIR="/usr/local/Cellar/qt/5.13.2/"

**Comment by sarndt** [comment]
> It appeared that I had to unzip dlt-viewer from scratch, because cmake cache prevented from correct build of application on macOS
> 
> However here are my parameters from bash_profile in case anyone might require them:
> 
> export CMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.13.2/
> export Qt5_DIR="/usr/local/Cellar/qt/5.13.2/"
> export QtDIR="/usr/local/Cellar/qt/5.13.2/"

Thanks for this, this actually helped me, I ran into the same issue.
It wasn't necessary for me to clone the project anew or anything, but I needed to delete the `CMakeCache.txt` that was probably there created during one of my previous attempts to compile.
