### ISSUE TITLE
Why is the version UNSTABLE?

### ISSUE THREAD

**Issue by Mehmetcanss** [GENIVI/dlt-viewer#48]

**Comment by Mehmetcanss** [comment]
I just built the DLT Viewer, However the version is UNSTABLE?
Why? Is there no stable version?

**Comment by alexmucde** [comment]
A stable release v2.19.0 is planned for the next days, but we are waiting still for feedback from testers , see also #16 .
Normally every commit should be stable, as we perform CI.
