### ISSUE TITLE
Searching for case-sensitive string - after typing the wrong case first and then correcting it - is not possible

### ISSUE THREAD

**Issue by SvenLuebke** [GENIVI/dlt-viewer#71]
Hi!

Due to the QCompleter, which is set to Qt::CaseInsensitive by
`newCompleter->setCaseSensitivity(Qt::CaseInsensitive);`
(in mainwindow.cpp) it's not easily possible to do a case sensitive search after typing the wrong case in the searchList. The QCompleter will always replace the string with the first "wrong" entered string.

I just commented it out and it's working as I would expect!

BR,
Sven

**Comment by alexmucde** [comment]
Fixed with PR #80
