### ISSUE TITLE
provide binaries for releases

### ISSUE THREAD

**Issue by Hades32** [GENIVI/dlt-viewer#81]
For most people there is no reason to build this from scratch...

**Comment by alexmucde** [comment]
There are now builds for Windows available under

https://ci.appveyor.com/project/alexmucde/dlt-viewer/build/artifacts

There is a build also available for Ubuntu

https://ci.appveyor.com/project/alexmucde/dlt-viewer-3

But with now Arifacts yet.

**Comment by Hades32** [comment]
Great, thank you very much !

Will this be interested here as GitHub releases? Otherwise it feels a little unofficial...

Also, do you plan, OS X builds, too?

**Comment by alexmucde** [comment]
No OS X build planned.
