### ISSUE TITLE
ECU connect[Connection refused]

### ISSUE THREAD

**Issue by saitamo** [GENIVI/dlt-viewer#84]
dlt-daemon version: 2.18.4 STABLE, Target IP: 192.168.1.10
dlt-viewer version: 2.19.0 UNSTABLE, PC IP: 192.168.1.100

The network on both sides can be Ping. I have an example program that circulates log output all the time. when I choose TCP connection, the dlt-viewer always show the connection refused. But I choose UDP connection, dlt-viewer connected the target device is successful, but displayed control type and dlt-viewer was refreshed every 5s. 
can you help me to analyse it. Thanks.
![Capture](https://user-images.githubusercontent.com/17609408/71766157-db77f500-2f37-11ea-98e7-d69ad5bc0737.PNG)

**Comment by alexmucde** [comment]
I think this is a network issue on your side.
Please close ticket if it is already solved.

**Comment by alexmucde** [comment]
No feedback anymore, please reopen, if this is still an issue.
