### ISSUE TITLE
incorrect scaling on high dpi display

### ISSUE THREAD

**Issue by markus-i** [GENIVI/dlt-viewer#86]
Easily explained: I am on a high dpi display (3840x2160) in Windows 10. Windows recommends a display scaling of 150% (which is more of a minimum). The result in dlt-viewer is horrible: the text is scaled, but the bounding boxes of the tables aren't. Manual/automatic adjustment of the width is possible, but not of the height, with the result that the characters are squeezed into the lines, and characters going below the baseline (like q, g or y) are cut off.

DLT version is a customized (for one of our plugins) version of 2.19.0, built with QT 5.5.1

Question: does DLT (and QT) support high dpi displays and if yes, any suggestions on what we could do to get a reasonable display again?

![dltviewer](https://user-images.githubusercontent.com/44025590/72731404-f67f7180-3b93-11ea-9cd6-32c32debf81b.jpg)

**Comment by alexmucde** [comment]
Hi Markus,

i tried this at my UHD monitor at home with following build:

https://ci.appveyor.com/project/alexmucde/dlt-viewer-2/build/artifacts

MSVC2017 Qt5.13.2

I used 150% upscaling. I get a different result than you.

Only the DLT message table view looks ugly, it tries to upscale the Fond, perhaps we can try to change the Fond, perhaps also configurable in the seetings.

The search table view looks ok.

Alex

**Comment by alexmucde** [comment]
Pushed to master new feature to set the Font and the height of the table sections.

You can try the following build.

https://ci.appveyor.com/project/alexmucde/dlt-viewer-2/build/artifacts

Tried this on my UHD monitor and works fine.

Please reopen if this still does not fix your issue.

**Comment by markus-i** [comment]
Thank you. I'll check it.
