### ISSUE TITLE
Plugins are not working on Mac OS

### ISSUE THREAD

**Issue by FaniBhushan** [GENIVI/dlt-viewer#87]
![Screenshot 2020-01-23 at 4 16 34 PM](https://user-images.githubusercontent.com/32452437/72996934-d7831880-3dfb-11ea-910f-178e177d6aa0.png)
after providing the path of the plugins binary and then restarting the dlt-viewer, the plugins are not loaded and plugins panel is empty.

**Comment by alexmucde** [comment]
Sorry we have no MacOs available.
Anyone from the community can help?

**Comment by alexmucde** [comment]
No feedback, please reopen, if this is still an issue.

**Comment by FaniBhushan** [comment]
@alexmucde : This issue still exists if built on macos with cmake.
building with qmake with '-r' option builds this in release and it solves the issue.
Should I update the INSTALL.txt
