### ISSUE TITLE
Can't be build on macos currently

### ISSUE THREAD

**Issue by marudor** [GENIVI/dlt-viewer#93]
The following line is a Problem for MacOS User:
https://github.com/GENIVI/dlt-viewer/blob/c54822fc47a8a7a3eb95d0f1adcc9ab0bde33b9e/src/src.pro#L23

ld does not accept equal sign here.
It works if you cange:
`-rpath=.` to `-rpath .`

I'm not sure if this would work for other platforms - thats why this is not a PR.

**Comment by alexmucde** [comment]
Fixed now.
