### ISSUE TITLE
Filter with regular expression not working

### ISSUE THREAD

**Issue by ZiadRhouma** [GENIVI/dlt-viewer#99]
if I set a payload filter with regular expressions
, then no messages are shown in the DLT viewer, even though the messages already exist.

<img width="481" alt="DLT_Viewer_messages" src="https://user-images.githubusercontent.com/63190296/78473567-f9751180-7741-11ea-8125-508c5e2580cc.png">
<img width="571" alt="DLT_Viewer_regex" src="https://user-images.githubusercontent.com/63190296/78473569-fc700200-7741-11ea-8a6e-426919b439c3.png">
<img width="662" alt="DLT_Viewer_with_filter" src="https://user-images.githubusercontent.com/63190296/78473570-fed25c00-7741-11ea-825e-14a221a494da.png">

**Comment by alexmucde** [comment]
We are using the QRegularExpression class from Qt libary. According to the Qt doumentation the regular expression feature CaretAtZero you want to use is not supported:

https://doc.qt.io/qt-5/qregularexpression.html#caret-modes

**Comment by bazurbat** [comment]
Hi! This is simply a bug, I've just made a PR (#102) which fixes the problem. Please check it out. It looks like it's doing what it is supposed to do with the caret for the logs which I have at least.

**Comment by alexmucde** [comment]
#102 will solve this issue
